AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  popashotlogin:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::923532089598:role/service-role/pop-a-shot-iam-role'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /login
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /login
            Method: POST
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
